name: login_page
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  equatable: ^0.2.6
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  #build_runner: ^1.4.0
  #build_web_compilers: ^2.0.0
  #pedantic: ^1.0.0

flutter:
  assets:
    - assets/